#-------------------------------
# General Site Settings
title: BoxBeez - Blog
logo: logo192.png 
description: Blog from Boxbeez - a shopping and international shipping service from India

#-------------------------------
# Author Settings
author:
  name: Boxbeez
  image: IndiaMap.jpg
  say-hello: Hello, We're from <strong>BoxBeez</strong>
  bio: We strive to bring quality Indian products to your doorstep - fresh and fast! We bring this blog to you help you finding the right products for you.


#-------------------------------
# Contact links
email: mailto:support@boxbeez.com
facebook: https://www.facebook.com/people/BoxBeez/100094932040940/
instagram: https://www.instagram.com/boxbeez/
whatsapp: https://wa.me/15122003760



#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
